### ISSUE TITLE
replace types.string

### ISSUE THREAD

**Issue by alexjwilliams** [Oak-Digital/nixos-ip-whitelist-firewall#2]
As the title says. ``string`` is deprecated and its usage here: https://github.com/Oak-Digital/nixos-ip-whitelist-firewall/blob/a36402d8ddb149b51be447aded46c7b4dc6071fb/modules/ip-whitelist-firewall.nix#L18 causes the following warning: ``evaluation warning: The type `types.string` is deprecated. See https://github.com/NixOS/nixpkgs/pull/66346 for better alternative   ##types.``

**Comment by Alexnortung** [comment]
Thanks! it has been released in `v0.0.5`
